name: SignWarp
version: '${project.version}'
description: Warp tp plugin on signs
author: SiriusB_
website: http://discord.nb.studio/
folia-supported: true
api-version: '1.20'
main: fr.nbstudio.signwarp.SignWarp
softdepend:
  - Vault
commands:
  signwarp:
    description: "Manage SignWarp commands"
    usage: "/signwarp <subcommand>"
    aliases: ["sw"]
permissions:
  signwarp.*:
    children:
      - signwarp.create
      - signwarp.use
  signwarp.create:
    description: "Allows you to create warp signs"
    default: op
  signwarp.use:
    description: "Allow uses of warp signs"
    default: true
  signwarp.reload:
    description: "Allows you to reload the SignWarp configuration"
    default: op
  signwarp.admin:
    description: "Allows access to the warp management GUI"
    default: op
  signwarp.limit.unlimited:
    description: "Allows unlimited warp creation"
    default: op